version: "2.0"
services:

  elasticsearch:
    image: amsterdam/elasticsearch6
    command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  database:
    image: amsterdam/postgres
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: signals
      POSTGRES_USER: signals
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  rabbit:
    image: rabbitmq:3
    ports:
     - "5672:5672"
    environment:
     - RABBITMQ_ERLANG_COOKIE='secret cookie here'
     - RABBITMQ_DEFAULT_USER=signals
     - RABBITMQ_DEFAULT_PASS=insecure
     - RABBITMQ_DEFAULT_VHOST=vhost

  celery:
    build: ./api
    links:
      - database
      - rabbit
      - elasticsearch
    environment:
      - DB_NAME=signals
      - DB_PASSWORD=insecure
      - EMAIL_BACKEND=django.core.mail.backends.locmem.EmailBackend
      - DJANGO_SETTINGS_MODULE=signals.settings.development
      - ELASTIC_HOST=elasticsearch:9200
    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    command: celery -A signals worker -l debug

  celery_beat:
    build: ./api
    links:
      - database
      - rabbit
      - elasticsearch
    environment:
      - DB_NAME=signals
      - DB_PASSWORD=insecure
      - EMAIL_BACKEND=django.core.mail.backends.locmem.EmailBackend
      - DJANGO_SETTINGS_MODULE=signals.settings.development
      - ELASTIC_HOST=elasticsearch:9200
    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    command: celery -A signals beat -l info --pidfile /app/celerybeat.pid

  api:
    build: ./api
    ports:
      - "8000:8000"
    links:
      - database
      - rabbit
      - elasticsearch
    environment:
      - DB_NAME=signals
      - DB_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/signals/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=signals.wsgi:application
      - DJANGO_SETTINGS_MODULE=signals.settings.development
      - SIGMAX_AUTH_TOKEN
      - SIGMAX_SERVER
      - ELASTIC_HOST=elasticsearch:9200
    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    command: uwsgi --py-auto-reload=1

  import:
    build: ./import
    links:
      - database
    environment:
      - DB_NAME=signals
      - DB_PASSWORD=insecure
