version: '2.0'
services:

  database:
    image: amsterdam/postgres
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: signals
      POSTGRES_USER: signals
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  rabbit:
    image: rabbitmq:3
    ports:
     - "5672:5672"
    environment:
     - RABBITMQ_ERLANG_COOKIE='secret cookie here'
     - RABBITMQ_DEFAULT_USER=signals
     - RABBITMQ_DEFAULT_PASS=insecure
     - RABBITMQ_DEFAULT_VHOST=vhost

  celery:
    build: ./api
    links:
      - database
      - rabbit
    environment:
      - DB_NAME=meldingen
      - DB_PASSWORD=insecure
      - EMAIL_HOST
      - EMAIL_HOST_PASSWORD
      - EMAIL_HOST_USER
      - EMAIL_PORT
      - EMAIL_USE_SSL
      - EMAIL_USE_TLS
      - DJANGO_SETTINGS_MODULE=signals.settings.development
    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    command: celery -A signals worker -l info

  celery_beat:
    build: ./api
    links:
      - database
      - rabbit
    environment:
      - DB_NAME=meldingen
      - DB_PASSWORD=insecure
      - EMAIL_HOST
      - EMAIL_HOST_PASSWORD
      - EMAIL_HOST_USER
      - EMAIL_PORT
      - EMAIL_USE_SSL
      - EMAIL_USE_TLS
      - DJANGO_SETTINGS_MODULE=signals.settings.development
    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    command: celery -A signals beat -l info --pidfile /tmp/celerybeat.pid

  api:
    build: ./api
    ports:
      - "8000:8000"
    links:
      - database
      - rabbit
    environment:
      - DB_NAME=signals
      - DB_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/signals/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=signals.wsgi:application
      - DJANGO_SETTINGS_MODULE=signals.settings.development
      - SIGMAX_AUTH_TOKEN
      - SIGMAX_SERVER

      # For ZDS:
      - ZTC_HOST
      - ZTC_PORT
      - ZTC_SCHEME
      - ZTC_CLIENT_ID
      - ZTC_CLIENT_SECRET

      - ZTC_CATALOGUS_ID
      - ZTC_ZAAKTYPE_ID
      - ZTC_INFORMATIEOBJECTTYPE_ID

      - ZRC_HOST
      - ZRC_PORT
      - ZRC_SCHEME
      - ZRC_CLIENT_ID
      - ZRC_CLIENT_SECRET

      - DRC_HOST
      - DRC_PORT
      - DRC_SCHEME
      - DRC_CLIENT_ID
      - DRC_CLIENT_SECRET

    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    command: uwsgi --py-auto-reload=1

  import:
    build: ./import
    links:
      - database
    environment:
      - DB_NAME=meldingen
      - DB_PASSWORD=insecure
