# Generated by Django 2.1.5 on 2019-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0030_subcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='departments',
            field=models.ManyToManyField(null=True, to='signals.Department'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='handling',
            field=models.CharField(
                blank=True,
                choices=[
                    ('A3DMC', 'A3DMC'),
                    ('A3DEC', 'A3DEC'),
                    ('A3WMC', 'A3WMC'),
                    ('A3WEC', 'A3WEC'),
                    ('I5DMC', 'I5DMC'),
                    ('STOPEC', 'STOPEC'),
                    ('KLOKLICHTZC', 'KLOKLICHTZC'),
                    ('GLADZC', 'GLADZC'),
                    ('A3DEVOMC', 'A3DEVOMC'),
                    ('WS1EC', 'WS1EC'),
                    ('WS2EC', 'WS2EC'),
                    ('REST', 'REST')
                ],
                max_length=20,
                null=True
            ),
        ),
    ]
