# Generated by Django 2.1.5 on 2019-02-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0031_auto_20190205_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='image',
        ),
    ]
